AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NewsSentimentLambda

  Sample SAM Template for NewsSentimentLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  NewsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: news_sentiment_app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonS3FullAccess 
        - AmazonDynamoDBFullAccess 
        - ComprehendFullAccess 
        - AWSLambdaBasicExecutionRole 

      Events:
        News:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /news
            Method: get
        Schedule:
          Type: Schedule
          Properties:
            Description: Cloudwatch schedule trigger lambda
            Name: FindNewsScheduler
            Schedule: rate(5 minutes)       
            Input: '[{"action":"insert news"}]'

  DynamoNewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'news'
      AttributeDefinitions:
        - 
          AttributeName: "title"
          AttributeType: "S"
        - 
          AttributeName: "timestamp"
          AttributeType: "S"


      KeySchema:
        - 
          AttributeName: "title"
          KeyType: "HASH"
        - 
          AttributeName: "timestamp"
          KeyType: "RANGE"
      
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NewsApi:
    Description: "API Gateway endpoint URL for Prod stage for News function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/news/"
  NewsFunction:
    Description: "News Lambda Function ARN"
    Value: !GetAtt NewsFunction.Arn
  NewsFunctionIamRole:
    Description: "Implicit IAM Role created for News function"
    Value: !GetAtt NewsFunctionRole.Arn
